name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install PM2 if missing
      run: |
        if ! command -v pm2 &> /dev/null
        then
          sudo npm install -g pm2
        fi

    # Backend
    - name: Install Backend Dependencies
      working-directory: backend
      run: |
        npm install --global yarn
        yarn install

    - name: Create Backend .env
      working-directory: backend
      run: |
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env

    # Frontend
    - name: Install Frontend Dependencies
      working-directory: frontend
      run: |
        yarn install

    - name: Disable CI warnings
      run: echo "CI=false" >> $GITHUB_ENV

    - name: Build Frontend
      working-directory: frontend
      run: yarn build

    # PM2 Safe Restart
    - name: Restart Backend Safely
      run: |
        pm2 restart backend || pm2 start "npm run start" --name backend

    - name: Restart Frontend Safely
      run: |
        pm2 restart frontend || pm2 serve frontend/build 3000 --name frontend --spa

    - name: Save PM2 State
      run: pm2 save
